### ISSUE TITLE
'networks' configuration issue

### ISSUE THREAD

**Issue by artemCleverua** [rackspace/rack#401]
Hi.
Less then a month ago I made heat template with configurations. This Heat template was correct and Rackspace orchestration stack was created.
Today with almost the same heat template "rack orchestration stack create" returns:

`error Invalid request due to incorrect syntax or missing required parameters.`

Directly from Rackspace Orchestration New Stack Templates I have next result:

`Failed to validate: One of the properties "network", "port" or "subnet" should be set for the specified network of server "0".`

heat_template_version: 2014-10-16

```
resources:
  servers:
    properties:
      count: 1
      resource_def:
        properties:
          config_drive: "true"
          flavor:
            get_param: flavor
          image: 44aff7ff-29f3-443d-8da8-9353d47b4b17
          key_name:
            get_param: ssh_key_name
          name: application-name-staging-%index%
          networks:
          - uuid: 00000000-0000-0000-0000-000000000000
          - uuid: 11111111-1111-1111-1111-111111111111
```

Is this a backward compatibility issue or there was some changes that can cause current error?
