### ISSUE TITLE
Orchestration stack create fails

### ISSUE THREAD

**Issue by queil** [rackspace/rack#456]
Trying to issue the following command (Windows 10, Powershell)
``` code
.\rack.exe orchestration stack create --name RackTest --template-file teststack.yaml --username XX

XX --api-key YYYY
```
It fails with the following error:
``` code
error   Get c:\Users\XXXXX\Desktop: unsupported protocol scheme "c"
```

When trying to specify file name with the file:// scheme it fails with:

``` code
error   Data in neither json nor yaml format.
```

My template looks like the following:
``` yaml
heat_template_version: 2013-05-23

description: |
  Template for the Heat Smoke Test

resources:

  random_key_name:
    type: OS::Heat::RandomString
    properties:
      length: 8
```
